spark_locals_without_parens = [
  capability: 1,
  capability: 2,
  category: 1,
  compensation: 1,
  config_schema: 1,
  data: 1,
  default_slices: 1,
  description: 1,
  job_id: 1,
  match: 1,
  name: 1,
  on_conflict: 1,
  otp_app: 1,
  output_schema: 1,
  path: 1,
  plugin: 1,
  priority: 1,
  requires: 2,
  requires: 3,
  route: 2,
  route: 3,
  schedule: 2,
  schedule: 3,
  schema: 1,
  signal: 1,
  signal: 2,
  static: 1,
  storage: 1,
  subscription: 2,
  subscription: 3,
  tags: 1,
  timezone: 1,
  topology: 1,
  tz: 1,
  vsn: 1
]

# Used by "mix format"
[
  import_deps: [:ash, :spark],
  plugins: [Spark.Formatter],
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  locals_without_parens: spark_locals_without_parens,
  export: [locals_without_parens: [jido_slice: 1] ++ spark_locals_without_parens]
]
