defmodule Jido.Pod.Info do
  @moduledoc """
  Introspection for pod-extended agent modules.

  `pod_topology/1` and `pod_options/1` are auto-generated by
  `Spark.InfoGenerator` from the `:pod` section schema contributed by
  `Jido.Pod`. Because `Jido.Pod.Transformers.ResolveTopology` writes
  the normalized `%Jido.Pod.Topology{}` back into the section's opts,
  `pod_topology/1` returns the normalized struct (with the agent's
  name applied), not the raw user-declared map.

  `pod?/1` is hand-written and derived from the agent's capability
  set: any agent that mounts a slice advertising `:pod` is a pod.
  """

  use Spark.InfoGenerator, extension: Jido.Pod, sections: [:pod]

  @spec pod?(module()) :: boolean()
  def pod?(module) when is_atom(module) do
    :pod in Jido.Dsl.Agent.Info.capabilities(module)
  end
end
